version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - my-net

  app:
    image: ${DOCKER_REGISTRY-}bookstore_borrowing_service
    build:
      context: .
      dockerfile: BookStore.BorrowingService\BookStore.BorrowingService.Api/Dockerfile
    container_name: bookstore_borrowing_service
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoDb__ConnectionString=mongodb://mongo:27017
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
    networks:
      - my-net

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my-net

networks:
  my-net:
    driver: bridge

volumes:
  mongodb_data:
